##
## EPITECH PROJECT, 2022
## my_printf_Makefile
## File description:
## my_printf_Makefile
##

all:
	make -C solver/
	make -C generator/

clean:
	make clean -C solver/
	make clean -C generator/
fclean:
	make fclean -C solver/
	make fclean -C generator/
	clear
re:
	make re -C solver/
	make re -C generator/

tests_run:
	make tests_run -C solver/
	make tests_run -C generator/
